/**
 * ravenCatalogPublisher — PRD-T-S S5 closed-loop distribution.
 *
 * Opt-in: opens a GitHub PR that adds a certified agent to the Stellar Raven
 * catalog (`catalog/agents/<slug>.json`), so a certified agent graduates back
 * into the SDF-endorsed catalog it trained on.
 *
 * Entirely feature-flagged + best-effort: returns null (never throws) when the
 * flag is off, GITHUB_TOKEN is unset, or any API call fails — certification is
 * never blocked by publishing.
 *
 * SOLID: SRP — owns only the GitHub PR flow. No DB, no training logic.
 */

import { logger } from '../lib';

const API = 'https://api.github.com';
const UPSTREAM = process.env.RAVEN_CATALOG_REPO ?? 'kalepail/stellar-raven';
const APP_URL = process.env.PUBLIC_APP_URL ?? 'http://localhost:3000';

export interface RavenPublishInput {
  slug: string;
  scoreBps: number;
  certHash: string;
  agentId: string;
}

export interface IRavenCatalogPublisher {
  publish(input: RavenPublishInput): Promise<string | null>;
}

class RavenCatalogPublisher implements IRavenCatalogPublisher {
  async publish(input: RavenPublishInput): Promise<string | null> {
    if (process.env.FEATURE_TRAINING_RAVEN_PUBLISH !== 'true') return null;
    const token = process.env.GITHUB_TOKEN?.trim();
    if (!token) {
      logger.info({ slug: input.slug }, 'raven:publish:skipped_no_token');
      return null;
    }
    // Fork target: publish from the platform's own fork (RAVEN_CATALOG_FORK),
    // then PR into UPSTREAM. Requires the fork to exist + token to own it.
    const fork = process.env.RAVEN_CATALOG_FORK;
    if (!fork) {
      logger.info({}, 'raven:publish:skipped_no_fork');
      return null;
    }
    try {
      const branch = `certify-${input.slug}-${input.scoreBps}`;
      const baseSha = await this.defaultBranchSha(token, fork);
      if (!baseSha) return null;
      await this.createBranch(token, fork, branch, baseSha);
      await this.putFile(token, fork, branch, input);
      return await this.openPr(token, fork, branch, input.slug);
    } catch (err) {
      logger.warn({ err: (err as Error).message, slug: input.slug }, 'raven:publish:failed');
      return null;
    }
  }

  private async gh(token: string, path: string, init?: RequestInit): Promise<Response> {
    return fetch(`${API}${path}`, {
      ...init,
      headers: {
        authorization: `Bearer ${token}`,
        accept: 'application/vnd.github+json',
        'content-type': 'application/json',
        ...(init?.headers ?? {}),
      },
    });
  }

  private async defaultBranchSha(token: string, repo: string): Promise<string | null> {
    const repoRes = await this.gh(token, `/repos/${repo}`);
    if (!repoRes.ok) return null;
    const { default_branch } = (await repoRes.json()) as { default_branch: string };
    const refRes = await this.gh(token, `/repos/${repo}/git/ref/heads/${default_branch}`);
    if (!refRes.ok) return null;
    return ((await refRes.json()) as { object: { sha: string } }).object.sha;
  }

  private async createBranch(token: string, repo: string, branch: string, sha: string): Promise<void> {
    await this.gh(token, `/repos/${repo}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha }),
    });
  }

  private async putFile(
    token: string,
    repo: string,
    branch: string,
    input: RavenPublishInput,
  ): Promise<void> {
    const content = {
      slug: input.slug,
      source: 'openx-s',
      certified: true,
      score_bps: input.scoreBps,
      certificate_hash: input.certHash,
      agent_url: `${APP_URL}/agent/${input.agentId}`,
    };
    await this.gh(token, `/repos/${repo}/contents/catalog/agents/${input.slug}.json`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `Add certified OpenX-S agent: ${input.slug}`,
        content: Buffer.from(JSON.stringify(content, null, 2)).toString('base64'),
        branch,
      }),
    });
  }

  private async openPr(token: string, fork: string, branch: string, slug: string): Promise<string | null> {
    const owner = fork.split('/')[0];
    const res = await this.gh(token, `/repos/${UPSTREAM}/pulls`, {
      method: 'POST',
      body: JSON.stringify({
        title: `Add certified OpenX-S agent: ${slug}`,
        head: `${owner}:${branch}`,
        base: 'main',
        body: `Certified Stellar Agent from OpenX-S. Auto-generated by the training pipeline.`,
      }),
    });
    if (!res.ok) return null;
    return ((await res.json()) as { html_url: string }).html_url;
  }
}

export const ravenCatalogPublisher: IRavenCatalogPublisher = new RavenCatalogPublisher();
